my_app/urls.py
from django.urls import path
from my_app import views

app_name='my_app'
urlpatterns=[
    path('',views.SchoolListView.as_view(),name='list'),
    path('?P<pk>-\d+',views.SchoolDetailView.as_view(),name='detail'),
    path('create/',views.SchoolCreateView.as_view(),name='create'),
    path('update/?P<pk>-\d+',views.SchoolUpdateView.as_view(),name='update'),
     path('delete/?P<pk>-\d+',views.SchoolDeleteView.as_view(),name='delete'),
]

my_project/urls.py
from django.contrib import admin
from django.urls import path,include
from my_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.indexview.as_view()),
    path('my_app/',include('my_app.urls',namespace='my_app')),
]

my_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class school(models.Model):
    name=models.CharField(max_length=264)
    principal=models.CharField(max_length=264)
    location=models.CharField(max_length=264)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('my_app:detail',kwargs={'pk':self.pk})

class students(models.Model):
    name=models.CharField(max_length=264)
    age=models.PositiveIntegerField()
    school=models.ForeignKey(school,on_delete=models.CASCADE,related_name='students')

    def __str__(self):
        return self.name

my_app/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (View,TemplateView,
                                 ListView,DetailView,
                                 CreateView,UpdateView,
                                 DeleteView)
from my_app import models


class indexview(TemplateView):
    template_name='index.html'

class SchoolListView(ListView):
    context_object_name='schools'
    model=models.school

class SchoolDetailView(DetailView):
    context_object_name='school_details'
    model=models.school
    template_name='my_app/school_details.html'

class SchoolCreateView(CreateView):
    fields=('name','principal','location')
    model=models.school

class SchoolUpdateView(UpdateView):
    fields=('name','principal')
    model=models.school

class SchoolDeleteView(DeleteView):
    model=models.school
    success_url=reverse_lazy('my_app:list')

my_app/templates/my_app/my_app_base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title>school details page</title>
    </head>
    <body>
        <nav class="navbar navbar-default navbar-static-top">
            <h1>this is base page in my app</h1>
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'my_app:list' %}">schools</a></li>
                <li><a class="navbar-link" href="{% url 'admin:index' %}">admin</a></li>
                <li><a href="#"></a></li>
            </ul>
        </nav>
        {% block body_block %}
        <h1>this is my app base html</h1>
        {% endblock %}
    </body>
</html>

my_app/templates/my_app/school_confirm_delete.html
{% extends 'my_app/my_app_base.html'%}
{% block body_block %}
<h1>delete{{ school.name}}?</h1>
<form method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="delete">
    <a href="{% url 'my_app:detail' pk=school.pk %}">cancel</a>
</form>

my_app/templates/my_app/school_details.html
{% extends "my_app/my_app_base.html" %}
{% block body_block %}
<div class="jumbotron">
    <h1>welcome to the school details page</h1>
    <h2>school details:</h2>
    <p>Name:{{school_details.name}}</p>
    <p>Principal:{{school_details.principal}}</p>
    <p>Location:{{school_details.location}}</p>
    <h3>students:</h3>

    {% for student in school_details.students.all %}
    <p>{{student.name}} who is {{student.age}} years old.</p>
    {% endfor %}
</div>
<div class="container">
    <p><a class="btn btn-warning" href="{% url 'my_app:update' pk=school_details.pk %}">update</a> </p>
</div>
{% endblock %}

my_app/templates/my_app/school_form.html
{% extends 'my_app/my_app_base.html' %}
{% block body_block %}
<h1>
    {% if not form.instance.pk %}
    Create school
    {% else %}
    Update school
    {% endif %}
</h1>
<form>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary" value="submit">
</form>
{% endblock %}

my_app/templates/my_app/school_list.html
{% extends "my_app/my_app_base.html" %}
{% block body_block %}
<div class="jumbotron">
<h1>welcome to list of schools list</h1>
<ol>
    {% for school in schools %}
    <h1><li>{{school.name}}</li></h1>
    {% endfor %}
</ol>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title>school details page</title>
    </head>
    <body>
            <nav class="navbar navbar-default navbar-static-top>
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'my_app:list' %}">schools</a></li>
                <li><a class="navbar-link" href="{% url 'admin:index' %}">admin</a></li>
                <li><a href="#"></a></li>
            </ul>
        </nav>
        {% block body_block %}
        <h1>this is project.html</h1>
        {% endblock %}
    </body>
</html>

templates/index.html
{% extends "base.html" %}
{% block body_block %}
<div class="jumbotron">
    <h1>welcome to home page.index html</h1>
</div>
{% endblock %}